-- Async job tracking for bookmark study-card generation

CREATE TABLE bookmark_study_card_jobs (
    job_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    bookmark_id    NUMBER NOT NULL,
    status         VARCHAR2(20) NOT NULL,
    error_message  VARCHAR2(2000),
    created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    started_at     TIMESTAMP,
    finished_at    TIMESTAMP,
    updated_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_bscj_bookmark FOREIGN KEY (bookmark_id)
        REFERENCES bookmarks (bookmark_id)
        ON DELETE CASCADE,
    CONSTRAINT chk_bscj_status CHECK (status IN ('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED'))
);

CREATE OR REPLACE TRIGGER trg_bscj_updated_at
BEFORE UPDATE ON bookmark_study_card_jobs
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE INDEX idx_bscj_bookmark_status ON bookmark_study_card_jobs (bookmark_id, status, created_at);

COMMIT;
