-- Bookmarks project schema

CREATE TABLE bookmarks (
    bookmark_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    url         VARCHAR2(2000) NOT NULL,
    title       VARCHAR2(500)  NOT NULL,
    category    VARCHAR2(100),
    starred     NUMBER(1) DEFAULT 0 NOT NULL,
    notes       CLOB,
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_bookmarks_url UNIQUE (url),
    CONSTRAINT chk_bookmarks_starred CHECK (starred IN (0, 1))
);

CREATE OR REPLACE TRIGGER trg_bookmarks_updated_at
BEFORE UPDATE ON bookmarks
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/

-- Dashboard card seed for /bookmarks project
MERGE INTO kv_store t
USING (
  SELECT 'bookmarks' AS item_key, 'Bookmarks' AS item_value, 'dashboard' AS category FROM dual
) s
ON (t.item_key = s.item_key)
WHEN MATCHED THEN
  UPDATE SET t.item_value = s.item_value, t.category = s.category, t.is_active = 'Y'
WHEN NOT MATCHED THEN
  INSERT (item_key, item_value, category, is_active)
  VALUES (s.item_key, s.item_value, s.category, 'Y');

COMMIT;
