-- Bookmark Study Cards feature schema + config

CREATE TABLE bookmark_study_cards (
    card_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    bookmark_id     NUMBER NOT NULL,
    card_no         NUMBER NOT NULL,
    question        VARCHAR2(500) NOT NULL,
    answer          CLOB NOT NULL,
    source_excerpt  CLOB,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_bsc_bookmark FOREIGN KEY (bookmark_id)
        REFERENCES bookmarks (bookmark_id)
        ON DELETE CASCADE,
    CONSTRAINT chk_bsc_card_no CHECK (card_no >= 1)
);

CREATE OR REPLACE TRIGGER trg_bsc_updated_at
BEFORE UPDATE ON bookmark_study_cards
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE INDEX idx_bsc_bookmark_no ON bookmark_study_cards (bookmark_id, card_no);

MERGE INTO kv_store t
USING (
  SELECT
    'BOOKMARK_STUDY_CARDS_MAX' AS item_key,
    '10' AS item_value,
    'Maximum number of study cards generated per bookmark' AS additional_info,
    'config' AS category
  FROM dual
) s
ON (t.item_key = s.item_key)
WHEN MATCHED THEN
  UPDATE SET
    t.item_value = NVL(t.item_value, s.item_value),
    t.additional_info = NVL(t.additional_info, s.additional_info),
    t.category = s.category,
    t.is_active = 'Y'
WHEN NOT MATCHED THEN
  INSERT (item_key, item_value, additional_info, category, is_active)
  VALUES (s.item_key, s.item_value, s.additional_info, s.category, 'Y');

COMMIT;
