-- Finance Tracker schema + seeds

CREATE TABLE ft_accounts (
    account_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_name   VARCHAR2(120) NOT NULL,
    account_type   VARCHAR2(20) NOT NULL,
    is_active      CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT chk_ft_accounts_type CHECK (account_type IN ('SAVINGS', 'CREDIT')),
    CONSTRAINT chk_ft_accounts_active CHECK (is_active IN ('Y', 'N'))
);

CREATE UNIQUE INDEX uq_ft_accounts_name ON ft_accounts (LOWER(account_name));

CREATE TABLE ft_transactions (
    transaction_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_text           CLOB,
    amount             NUMBER(14,2) NOT NULL,
    tx_date            DATE NOT NULL,
    category           VARCHAR2(120) DEFAULT 'uncategorized' NOT NULL,
    description        VARCHAR2(4000),
    account_id         NUMBER NULL,
    status             VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    direction          VARCHAR2(20) NOT NULL,
    is_active          CHAR(1) DEFAULT 'Y' NOT NULL,
    llm_processed_at   TIMESTAMP NULL,
    created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_ft_transactions_account FOREIGN KEY (account_id)
        REFERENCES ft_accounts(account_id)
        ON DELETE SET NULL,
    CONSTRAINT chk_ft_transactions_status CHECK (status IN ('PENDING', 'PROCESSED', 'FAILED', 'MANUAL')),
    CONSTRAINT chk_ft_transactions_direction CHECK (direction IN ('INCOME', 'EXPENSE')),
    CONSTRAINT chk_ft_transactions_active CHECK (is_active IN ('Y', 'N'))
);

CREATE TABLE ft_llm_calls (
    call_id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id           NUMBER NULL,
    model_name               VARCHAR2(120) NOT NULL,
    request_payload          CLOB,
    response_payload         CLOB,
    prompt_tokens            NUMBER,
    completion_tokens        NUMBER,
    total_tokens             NUMBER,
    latency_ms               NUMBER,
    http_status              NUMBER,
    cache_hit                CHAR(1) DEFAULT 'N' NOT NULL,
    error_message            VARCHAR2(4000),
    request_hash             VARCHAR2(128),
    normalized_result_json   CLOB,
    created_at               TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_ft_llm_calls_tx FOREIGN KEY (transaction_id)
        REFERENCES ft_transactions(transaction_id)
        ON DELETE SET NULL,
    CONSTRAINT chk_ft_llm_calls_cache CHECK (cache_hit IN ('Y', 'N'))
);

CREATE INDEX idx_ft_transactions_status ON ft_transactions(status);
CREATE INDEX idx_ft_transactions_date ON ft_transactions(tx_date);
CREATE INDEX idx_ft_transactions_updated ON ft_transactions(updated_at);
CREATE INDEX idx_ft_transactions_account ON ft_transactions(account_id);
CREATE INDEX idx_ft_transactions_active ON ft_transactions(is_active);
CREATE INDEX idx_ft_llm_calls_tx ON ft_llm_calls(transaction_id);
CREATE INDEX idx_ft_llm_calls_hash ON ft_llm_calls(request_hash, model_name);

CREATE OR REPLACE TRIGGER trg_ft_accounts_updated_at
BEFORE UPDATE ON ft_accounts
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_ft_transactions_updated_at
BEFORE UPDATE ON ft_transactions
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/

-- Dashboard card seed (k=ft, v=Finance Tracker, category=dashboard)
MERGE INTO kv_store t
USING (
  SELECT 'ft' AS item_key,
         'Finance Tracker' AS item_value,
         '{"icon":"fa-solid fa-wallet"}' AS additional_info,
         'dashboard' AS category
  FROM dual
) s
ON (t.item_key = s.item_key)
WHEN MATCHED THEN
  UPDATE SET t.item_value = s.item_value,
             t.additional_info = s.additional_info,
             t.category = s.category,
             t.is_active = 'Y'
WHEN NOT MATCHED THEN
  INSERT (item_key, item_value, additional_info, category, is_active)
  VALUES (s.item_key, s.item_value, s.additional_info, s.category, 'Y');

-- Dashboard card seed for FT Spend Tracker
MERGE INTO kv_store t
USING (
  SELECT 'ft_tracker' AS item_key,
         'Spend Tracker' AS item_value,
         '{"icon":"fa-solid fa-chart-line","order":4}' AS additional_info,
         'dashboard' AS category
  FROM dual
) s
ON (t.item_key = s.item_key)
WHEN MATCHED THEN
  UPDATE SET t.item_value = s.item_value,
             t.additional_info = s.additional_info,
             t.category = s.category,
             t.is_active = 'Y'
WHEN NOT MATCHED THEN
  INSERT (item_key, item_value, additional_info, category, is_active)
  VALUES (s.item_key, s.item_value, s.additional_info, s.category, 'Y');

-- Toggle to disable FT LLM processing
MERGE INTO kv_store t
USING (
  SELECT 'FT_DISABLE_LLM_PROCESSING' AS item_key,
         'N' AS item_value,
         'Set Y to disable Finance Tracker LLM batch processing' AS additional_info,
         'toggle' AS category
  FROM dual
) s
ON (t.item_key = s.item_key)
WHEN MATCHED THEN
  UPDATE SET t.item_value = s.item_value,
             t.additional_info = s.additional_info,
             t.category = s.category,
             t.is_active = 'Y'
WHEN NOT MATCHED THEN
  INSERT (item_key, item_value, additional_info, category, is_active)
  VALUES (s.item_key, s.item_value, s.additional_info, s.category, 'Y');

-- Optional model override key
MERGE INTO kv_store t
USING (
  SELECT 'FT_LLM_MODEL' AS item_key,
         'gemma-3-27b-it' AS item_value,
         'Finance Tracker LLM model id' AS additional_info,
         'config' AS category
  FROM dual
) s
ON (t.item_key = s.item_key)
WHEN MATCHED THEN
  UPDATE SET t.item_value = s.item_value,
             t.additional_info = s.additional_info,
             t.category = s.category,
             t.is_active = 'Y'
WHEN NOT MATCHED THEN
  INSERT (item_key, item_value, additional_info, category, is_active)
  VALUES (s.item_key, s.item_value, s.additional_info, s.category, 'Y');

-- Accounts context KV holder
MERGE INTO kv_store t
USING (
  SELECT 'ft_accounts' AS item_key,
         'FT Accounts' AS item_value,
         '{"account":[]}' AS additional_info,
         'config' AS category
  FROM dual
) s
ON (t.item_key = s.item_key)
WHEN MATCHED THEN
  UPDATE SET t.item_value = s.item_value,
             t.category = s.category,
             t.is_active = 'Y'
WHEN NOT MATCHED THEN
  INSERT (item_key, item_value, additional_info, category, is_active)
  VALUES (s.item_key, s.item_value, s.additional_info, s.category, 'Y');

COMMIT;
