-- Messenger project schema + seeds

CREATE TABLE messenger_messages (
    message_id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    message_text           CLOB NOT NULL,
    status                 VARCHAR2(20) NOT NULL,
    telegram_message_id    VARCHAR2(100),
    telegram_chat_id       VARCHAR2(120),
    http_status            NUMBER,
    response_payload       CLOB,
    error_message          VARCHAR2(4000),
    is_hidden              CHAR(1) DEFAULT 'N' NOT NULL,
    resend_of_message_id   NUMBER,
    created_at             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT chk_messenger_messages_status CHECK (status IN ('SENT', 'FAILED')),
    CONSTRAINT chk_messenger_messages_hidden CHECK (is_hidden IN ('Y', 'N')),
    CONSTRAINT fk_messenger_messages_resend_of FOREIGN KEY (resend_of_message_id)
        REFERENCES messenger_messages(message_id)
        ON DELETE SET NULL
);

CREATE INDEX idx_messenger_messages_status ON messenger_messages(status);
CREATE INDEX idx_messenger_messages_hidden ON messenger_messages(is_hidden);
CREATE INDEX idx_messenger_messages_created ON messenger_messages(created_at);
CREATE INDEX idx_messenger_messages_resend ON messenger_messages(resend_of_message_id);

CREATE OR REPLACE TRIGGER trg_messenger_messages_updated_at
BEFORE UPDATE ON messenger_messages
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/

-- Dashboard card seed
MERGE INTO kv_store t
USING (
  SELECT 'messenger' AS item_key,
         'Messenger' AS item_value,
         '{"icon":"fa-brands fa-telegram","order":6}' AS additional_info,
         'dashboard' AS category
  FROM dual
) s
ON (t.item_key = s.item_key)
WHEN MATCHED THEN
  UPDATE SET t.item_value = s.item_value,
             t.additional_info = s.additional_info,
             t.category = s.category,
             t.is_active = 'Y'
WHEN NOT MATCHED THEN
  INSERT (item_key, item_value, additional_info, category, is_active)
  VALUES (s.item_key, s.item_value, s.additional_info, s.category, 'Y');

-- Toggle to enable/disable Telegram send
MERGE INTO kv_store t
USING (
  SELECT 'ALLOW_TELEGRAM_SEND' AS item_key,
         'N' AS item_value,
         'Set Y to allow sending Telegram messages from Rover' AS additional_info,
         'toggle' AS category
  FROM dual
) s
ON (t.item_key = s.item_key)
WHEN MATCHED THEN
  UPDATE SET t.item_value = s.item_value,
             t.additional_info = s.additional_info,
             t.category = s.category,
             t.is_active = 'Y'
WHEN NOT MATCHED THEN
  INSERT (item_key, item_value, additional_info, category, is_active)
  VALUES (s.item_key, s.item_value, s.additional_info, s.category, 'Y');

-- Config key for Telegram bot token
MERGE INTO kv_store t
USING (
  SELECT 'TELEGRAM_BOT_TOKEN' AS item_key,
         '' AS item_value,
         'Telegram bot token used for sendMessage API calls' AS additional_info,
         'config' AS category
  FROM dual
) s
ON (t.item_key = s.item_key)
WHEN MATCHED THEN
  UPDATE SET t.additional_info = s.additional_info,
             t.category = s.category,
             t.is_active = 'Y'
WHEN NOT MATCHED THEN
  INSERT (item_key, item_value, additional_info, category, is_active)
  VALUES (s.item_key, s.item_value, s.additional_info, s.category, 'Y');

-- Config key for default Telegram chat id
MERGE INTO kv_store t
USING (
  SELECT 'TELEGRAM_DEFAULT_CHAT_ID' AS item_key,
         '' AS item_value,
         'Default Telegram chat ID used when sending messages' AS additional_info,
         'config' AS category
  FROM dual
) s
ON (t.item_key = s.item_key)
WHEN MATCHED THEN
  UPDATE SET t.additional_info = s.additional_info,
             t.category = s.category,
             t.is_active = 'Y'
WHEN NOT MATCHED THEN
  INSERT (item_key, item_value, additional_info, category, is_active)
  VALUES (s.item_key, s.item_value, s.additional_info, s.category, 'Y');

COMMIT;
