-- Rover: Consolidated DDL + Relationship Map (Oracle)
--
-- Purpose:
--   Single reference file to understand DB entities and relations used by this app.
--
-- Notes:
--   1) `kv_store` is heavily used by Rover (KV, toggles, dashboard, shortcuts, API keys/config)
--      but its CREATE TABLE DDL is not present in this repository.
--   2) This file focuses on application tables whose DDL exists in /sql.

--------------------------------------------------------------------------------
-- 0) EXTERNAL / PRE-EXISTING TABLE (NOT DEFINED HERE)
--------------------------------------------------------------------------------
-- kv_store (expected columns used by app):
--   item_key, item_value, additional_info, category, sub_category,
--   is_active, created_at, updated_at


--------------------------------------------------------------------------------
-- 1) SECONDARY BRAIN
--------------------------------------------------------------------------------

CREATE TABLE sb_folders (
    folder_id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_folder_id          NUMBER NULL,
    folder_name               VARCHAR2(255) NOT NULL,
    is_trashed                CHAR(1) DEFAULT 'N' NOT NULL,
    previous_parent_folder_id NUMBER NULL,
    created_at                TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at                TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT chk_sb_folders_trashed CHECK (is_trashed IN ('Y', 'N')),
    CONSTRAINT fk_sb_folders_parent FOREIGN KEY (parent_folder_id)
        REFERENCES sb_folders(folder_id)
);

CREATE INDEX idx_sb_folders_parent ON sb_folders(parent_folder_id);
CREATE INDEX idx_sb_folders_trashed ON sb_folders(is_trashed);
CREATE UNIQUE INDEX uq_sb_folders_sibling_name
ON sb_folders (NVL(parent_folder_id, -1), LOWER(folder_name), is_trashed);


CREATE TABLE sb_files (
    file_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folder_id          NUMBER NOT NULL,
    title              VARCHAR2(300) NOT NULL,
    content_md         CLOB NOT NULL,
    tags               VARCHAR2(1000),
    is_trashed         CHAR(1) DEFAULT 'N' NOT NULL,
    is_public          CHAR(1) DEFAULT 'N' NOT NULL,
    public_token       VARCHAR2(64),
    previous_folder_id NUMBER NULL,
    created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT chk_sb_files_trashed CHECK (is_trashed IN ('Y', 'N')),
    CONSTRAINT chk_sb_files_public CHECK (is_public IN ('Y', 'N')),
    CONSTRAINT fk_sb_files_folder FOREIGN KEY (folder_id)
        REFERENCES sb_folders(folder_id)
);

CREATE INDEX idx_sb_files_folder ON sb_files(folder_id);
CREATE INDEX idx_sb_files_trashed ON sb_files(is_trashed);
CREATE INDEX idx_sb_files_tags ON sb_files(tags);
CREATE UNIQUE INDEX uq_sb_files_public_token ON sb_files(public_token);
CREATE INDEX idx_sb_files_public_lookup ON sb_files(is_public, public_token);
CREATE UNIQUE INDEX uq_sb_files_folder_title
ON sb_files (folder_id, LOWER(title), is_trashed);


CREATE TABLE sb_file_links (
    file_id_low  NUMBER NOT NULL,
    file_id_high NUMBER NOT NULL,
    created_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_sb_file_links PRIMARY KEY (file_id_low, file_id_high),
    CONSTRAINT chk_sb_file_links_order CHECK (file_id_low < file_id_high),
    CONSTRAINT fk_sb_links_low FOREIGN KEY (file_id_low)
        REFERENCES sb_files(file_id),
    CONSTRAINT fk_sb_links_high FOREIGN KEY (file_id_high)
        REFERENCES sb_files(file_id)
);

CREATE INDEX idx_sb_links_high ON sb_file_links(file_id_high);


--------------------------------------------------------------------------------
-- 2) UPLOADS
--------------------------------------------------------------------------------

CREATE TABLE uploads_files (
    upload_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    title               VARCHAR2(500) NOT NULL,
    original_file_name  VARCHAR2(1000) NOT NULL,
    content_type        VARCHAR2(255),
    size_bytes          NUMBER(19) DEFAULT 0 NOT NULL,
    object_name         VARCHAR2(2000) NOT NULL,
    object_url          VARCHAR2(4000) NOT NULL,
    notes               CLOB,
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_uploads_object_name UNIQUE (object_name),
    CONSTRAINT chk_uploads_size_bytes CHECK (size_bytes >= 0)
);

CREATE INDEX idx_uploads_title ON uploads_files (LOWER(title));
CREATE INDEX idx_uploads_original_name ON uploads_files (LOWER(original_file_name));


CREATE TABLE uploads_sb_file_links (
    upload_id    NUMBER NOT NULL,
    file_id      NUMBER NOT NULL,
    created_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_uploads_sb_links PRIMARY KEY (upload_id, file_id),
    CONSTRAINT fk_uploads_sb_links_upload FOREIGN KEY (upload_id)
        REFERENCES uploads_files(upload_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_uploads_sb_links_file FOREIGN KEY (file_id)
        REFERENCES sb_files(file_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_uploads_sb_links_file ON uploads_sb_file_links(file_id);


--------------------------------------------------------------------------------
-- 3) FINANCE TRACKER
--------------------------------------------------------------------------------

CREATE TABLE ft_accounts (
    account_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_name   VARCHAR2(120) NOT NULL,
    account_type   VARCHAR2(20) NOT NULL,
    is_active      CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT chk_ft_accounts_type CHECK (account_type IN ('SAVINGS', 'CREDIT')),
    CONSTRAINT chk_ft_accounts_active CHECK (is_active IN ('Y', 'N'))
);

CREATE UNIQUE INDEX uq_ft_accounts_name ON ft_accounts (LOWER(account_name));


CREATE TABLE ft_transactions (
    transaction_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_text           CLOB,
    amount             NUMBER(14,2) NOT NULL,
    tx_date            DATE NOT NULL,
    category           VARCHAR2(120) DEFAULT 'uncategorized' NOT NULL,
    description        VARCHAR2(4000),
    account_id         NUMBER NULL,
    status             VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    direction          VARCHAR2(20) NOT NULL,
    is_active          CHAR(1) DEFAULT 'Y' NOT NULL,
    llm_processed_at   TIMESTAMP NULL,
    created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_ft_transactions_account FOREIGN KEY (account_id)
        REFERENCES ft_accounts(account_id)
        ON DELETE SET NULL,
    CONSTRAINT chk_ft_transactions_status CHECK (status IN ('PENDING', 'PROCESSED', 'FAILED', 'MANUAL')),
    CONSTRAINT chk_ft_transactions_direction CHECK (direction IN ('INCOME', 'EXPENSE')),
    CONSTRAINT chk_ft_transactions_active CHECK (is_active IN ('Y', 'N'))
);

CREATE INDEX idx_ft_transactions_status ON ft_transactions(status);
CREATE INDEX idx_ft_transactions_date ON ft_transactions(tx_date);
CREATE INDEX idx_ft_transactions_updated ON ft_transactions(updated_at);
CREATE INDEX idx_ft_transactions_account ON ft_transactions(account_id);
CREATE INDEX idx_ft_transactions_active ON ft_transactions(is_active);


CREATE TABLE ft_llm_calls (
    call_id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id           NUMBER NULL,
    model_name               VARCHAR2(120) NOT NULL,
    request_payload          CLOB,
    response_payload         CLOB,
    prompt_tokens            NUMBER,
    completion_tokens        NUMBER,
    total_tokens             NUMBER,
    latency_ms               NUMBER,
    http_status              NUMBER,
    cache_hit                CHAR(1) DEFAULT 'N' NOT NULL,
    error_message            VARCHAR2(4000),
    request_hash             VARCHAR2(128),
    normalized_result_json   CLOB,
    created_at               TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_ft_llm_calls_tx FOREIGN KEY (transaction_id)
        REFERENCES ft_transactions(transaction_id)
        ON DELETE SET NULL,
    CONSTRAINT chk_ft_llm_calls_cache CHECK (cache_hit IN ('Y', 'N'))
);

CREATE INDEX idx_ft_llm_calls_tx ON ft_llm_calls(transaction_id);
CREATE INDEX idx_ft_llm_calls_hash ON ft_llm_calls(request_hash, model_name);


CREATE TABLE uploads_ft_transaction_links (
    transaction_id   NUMBER NOT NULL,
    upload_id        NUMBER NOT NULL,
    created_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_uploads_ft_tx_links PRIMARY KEY (transaction_id, upload_id),
    CONSTRAINT fk_uploads_ft_tx_links_tx FOREIGN KEY (transaction_id)
        REFERENCES ft_transactions(transaction_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_uploads_ft_tx_links_upload FOREIGN KEY (upload_id)
        REFERENCES uploads_files(upload_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_uploads_ft_tx_links_upload ON uploads_ft_transaction_links(upload_id);


--------------------------------------------------------------------------------
-- 4) BOOKMARKS
--------------------------------------------------------------------------------

CREATE TABLE bookmarks (
    bookmark_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    url         VARCHAR2(2000) NOT NULL,
    title       VARCHAR2(500)  NOT NULL,
    category    VARCHAR2(100),
    starred     NUMBER(1) DEFAULT 0 NOT NULL,
    notes       CLOB,
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_bookmarks_url UNIQUE (url),
    CONSTRAINT chk_bookmarks_starred CHECK (starred IN (0, 1))
);


CREATE TABLE bookmark_study_cards (
    card_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    bookmark_id     NUMBER NOT NULL,
    card_no         NUMBER NOT NULL,
    question        VARCHAR2(500) NOT NULL,
    answer          CLOB NOT NULL,
    source_excerpt  CLOB,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_bsc_bookmark FOREIGN KEY (bookmark_id)
        REFERENCES bookmarks (bookmark_id)
        ON DELETE CASCADE,
    CONSTRAINT chk_bsc_card_no CHECK (card_no >= 1)
);

CREATE INDEX idx_bsc_bookmark_no ON bookmark_study_cards (bookmark_id, card_no);


CREATE TABLE bookmark_study_card_jobs (
    job_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    bookmark_id    NUMBER NOT NULL,
    status         VARCHAR2(20) NOT NULL,
    error_message  VARCHAR2(2000),
    created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    started_at     TIMESTAMP,
    finished_at    TIMESTAMP,
    updated_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_bscj_bookmark FOREIGN KEY (bookmark_id)
        REFERENCES bookmarks (bookmark_id)
        ON DELETE CASCADE,
    CONSTRAINT chk_bscj_status CHECK (status IN ('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED'))
);

CREATE INDEX idx_bscj_bookmark_status ON bookmark_study_card_jobs (bookmark_id, status, created_at);


--------------------------------------------------------------------------------
-- 5) MESSENGER
--------------------------------------------------------------------------------

CREATE TABLE messenger_messages (
    message_id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    message_text           CLOB NOT NULL,
    status                 VARCHAR2(20) NOT NULL,
    telegram_message_id    VARCHAR2(100),
    telegram_chat_id       VARCHAR2(120),
    http_status            NUMBER,
    response_payload       CLOB,
    error_message          VARCHAR2(4000),
    is_hidden              CHAR(1) DEFAULT 'N' NOT NULL,
    resend_of_message_id   NUMBER,
    created_at             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT chk_messenger_messages_status CHECK (status IN ('SENT', 'FAILED')),
    CONSTRAINT chk_messenger_messages_hidden CHECK (is_hidden IN ('Y', 'N')),
    CONSTRAINT fk_messenger_messages_resend_of FOREIGN KEY (resend_of_message_id)
        REFERENCES messenger_messages(message_id)
        ON DELETE SET NULL
);

CREATE INDEX idx_messenger_messages_status ON messenger_messages(status);
CREATE INDEX idx_messenger_messages_hidden ON messenger_messages(is_hidden);
CREATE INDEX idx_messenger_messages_created ON messenger_messages(created_at);
CREATE INDEX idx_messenger_messages_resend ON messenger_messages(resend_of_message_id);


--------------------------------------------------------------------------------
-- 6) RELATIONSHIP SUMMARY (ER QUICK MAP)
--------------------------------------------------------------------------------
-- sb_folders.parent_folder_id                 -> sb_folders.folder_id        (self tree)
-- sb_files.folder_id                          -> sb_folders.folder_id         (folder contains files)
-- sb_file_links.file_id_low                   -> sb_files.file_id             (file-to-file link)
-- sb_file_links.file_id_high                  -> sb_files.file_id             (file-to-file link)
-- uploads_sb_file_links.upload_id             -> uploads_files.upload_id      (M:N uploads<->sb_files)
-- uploads_sb_file_links.file_id               -> sb_files.file_id             (M:N uploads<->sb_files)
-- ft_transactions.account_id                  -> ft_accounts.account_id       (tx belongs to account)
-- ft_llm_calls.transaction_id                 -> ft_transactions.transaction_id (LLM audit for tx)
-- uploads_ft_transaction_links.transaction_id -> ft_transactions.transaction_id (M:N uploads<->ft_transactions)
-- uploads_ft_transaction_links.upload_id      -> uploads_files.upload_id      (M:N uploads<->ft_transactions)
-- bookmark_study_cards.bookmark_id            -> bookmarks.bookmark_id        (1:N cards per bookmark)
-- bookmark_study_card_jobs.bookmark_id        -> bookmarks.bookmark_id        (1:N jobs per bookmark)
-- messenger_messages.resend_of_message_id     -> messenger_messages.message_id (self resend chain)
