-- Secondary Brain schema (Oracle)

CREATE TABLE sb_folders (
    folder_id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_folder_id          NUMBER NULL,
    folder_name               VARCHAR2(255) NOT NULL,
    is_trashed                CHAR(1) DEFAULT 'N' NOT NULL,
    previous_parent_folder_id NUMBER NULL,
    created_at                TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at                TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT chk_sb_folders_trashed CHECK (is_trashed IN ('Y', 'N')),
    CONSTRAINT fk_sb_folders_parent FOREIGN KEY (parent_folder_id)
        REFERENCES sb_folders(folder_id)
);

CREATE INDEX idx_sb_folders_parent ON sb_folders(parent_folder_id);
CREATE INDEX idx_sb_folders_trashed ON sb_folders(is_trashed);
CREATE UNIQUE INDEX uq_sb_folders_sibling_name
ON sb_folders (NVL(parent_folder_id, -1), LOWER(folder_name), is_trashed);

CREATE TABLE sb_files (
    file_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folder_id          NUMBER NOT NULL,
    title              VARCHAR2(300) NOT NULL,
    content_md         CLOB NOT NULL,
    tags               VARCHAR2(1000),
    is_trashed         CHAR(1) DEFAULT 'N' NOT NULL,
    previous_folder_id NUMBER NULL,
    created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT chk_sb_files_trashed CHECK (is_trashed IN ('Y', 'N')),
    CONSTRAINT fk_sb_files_folder FOREIGN KEY (folder_id)
        REFERENCES sb_folders(folder_id)
);

CREATE INDEX idx_sb_files_folder ON sb_files(folder_id);
CREATE INDEX idx_sb_files_trashed ON sb_files(is_trashed);
CREATE INDEX idx_sb_files_tags ON sb_files(tags);
CREATE UNIQUE INDEX uq_sb_files_folder_title
ON sb_files (folder_id, LOWER(title), is_trashed);

CREATE TABLE sb_file_links (
    file_id_low  NUMBER NOT NULL,
    file_id_high NUMBER NOT NULL,
    created_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_sb_file_links PRIMARY KEY (file_id_low, file_id_high),
    CONSTRAINT chk_sb_file_links_order CHECK (file_id_low < file_id_high),
    CONSTRAINT fk_sb_links_low FOREIGN KEY (file_id_low)
        REFERENCES sb_files(file_id),
    CONSTRAINT fk_sb_links_high FOREIGN KEY (file_id_high)
        REFERENCES sb_files(file_id)
);

CREATE INDEX idx_sb_links_high ON sb_file_links(file_id_high);

CREATE OR REPLACE TRIGGER trg_sb_folders_updated_at
BEFORE UPDATE ON sb_folders
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_sb_files_updated_at
BEFORE UPDATE ON sb_files
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/
