-- Uploads project schema and seeds

CREATE TABLE uploads_files (
    upload_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    title               VARCHAR2(500) NOT NULL,
    original_file_name  VARCHAR2(1000) NOT NULL,
    content_type        VARCHAR2(255),
    size_bytes          NUMBER(19) DEFAULT 0 NOT NULL,
    object_name         VARCHAR2(2000) NOT NULL,
    object_url          VARCHAR2(4000) NOT NULL,
    notes               CLOB,
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_uploads_object_name UNIQUE (object_name),
    CONSTRAINT chk_uploads_size_bytes CHECK (size_bytes >= 0)
);

CREATE INDEX idx_uploads_title ON uploads_files (LOWER(title));
CREATE INDEX idx_uploads_original_name ON uploads_files (LOWER(original_file_name));

CREATE OR REPLACE TRIGGER trg_uploads_files_updated_at
BEFORE UPDATE ON uploads_files
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE TABLE uploads_sb_file_links (
    upload_id    NUMBER NOT NULL,
    file_id      NUMBER NOT NULL,
    created_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_uploads_sb_links PRIMARY KEY (upload_id, file_id),
    CONSTRAINT fk_uploads_sb_links_upload FOREIGN KEY (upload_id)
        REFERENCES uploads_files(upload_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_uploads_sb_links_file FOREIGN KEY (file_id)
        REFERENCES sb_files(file_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_uploads_sb_links_file ON uploads_sb_file_links(file_id);

-- Dashboard card seed for /uploads project
MERGE INTO kv_store t
USING (
  SELECT 'uploads' AS item_key,
         'Uploads' AS item_value,
         '{"icon":"fa-solid fa-cloud-arrow-up"}' AS additional_info,
         'dashboard' AS category
  FROM dual
) s
ON (t.item_key = s.item_key)
WHEN MATCHED THEN
  UPDATE SET t.item_value = s.item_value,
             t.additional_info = s.additional_info,
             t.category = s.category,
             t.is_active = 'Y'
WHEN NOT MATCHED THEN
  INSERT (item_key, item_value, additional_info, category, is_active)
  VALUES (s.item_key, s.item_value, s.additional_info, s.category, 'Y');

-- Toggle seed controlling OCI uploads
MERGE INTO kv_store t
USING (
  SELECT 'ALLOW_OCI_FILE_UPLOAD' AS item_key,
         'N' AS item_value,
         'Enable OCI object upload and delete operations for Uploads project' AS additional_info,
         'toggle' AS category
  FROM dual
) s
ON (t.item_key = s.item_key)
WHEN MATCHED THEN
  UPDATE SET t.item_value = s.item_value,
             t.additional_info = s.additional_info,
             t.category = s.category,
             t.is_active = 'Y'
WHEN NOT MATCHED THEN
  INSERT (item_key, item_value, additional_info, category, is_active)
  VALUES (s.item_key, s.item_value, s.additional_info, s.category, 'Y');

-- Config key for PAR URL (store actual PAR in additional_info)
MERGE INTO kv_store t
USING (
  SELECT 'oci_file_upload_par' AS item_key,
         'OCI File Upload PAR' AS item_value,
         '' AS additional_info,
         'config' AS category
  FROM dual
) s
ON (t.item_key = s.item_key)
WHEN MATCHED THEN
  UPDATE SET t.item_value = s.item_value,
             t.category = s.category,
             t.is_active = 'Y'
WHEN NOT MATCHED THEN
  INSERT (item_key, item_value, additional_info, category, is_active)
  VALUES (s.item_key, s.item_value, s.additional_info, s.category, 'Y');

COMMIT;
